### ISSUE TITLE
Time for IPv6

### ISSUE THREAD

**Issue by Schweinepriester** [dadavidson/dadavidson#1]
Hello there fine sir, Mr. Network Engineer!

I couldn't help but noticed that [on your profile](https://github.com/dadavidson) you state your location to be "127.0.0.1". While I chuckled at the ol' familiar home, I must inform you that [a newer protocol](https://en.wikipedia.org/wiki/IPv6) has been around for over 20 years and as such I implore you to make the switch with great haste!
I believe `::1` to be fitting - or perhaps you could choose [`localhost`, covering both bases](https://en.wikipedia.org/wiki/Localhost#Loopback)!

I remain with best wishes,
yours truly,

Schweinepriester

---

/s, this is meant to be humorous - pls switch to IPv6 and close this, kthxbai :D

**Comment by dadavidson** [comment]
I appreciate the humor! You do have a point though my friend. 

I will consider the changes you proposed and make the necessary changes shortly 😏

Respectfully,
D
